package com.guidinglight.nexusquant.trading.application.riskpreflight;

/**
 * GateW-3 diagnostic risk preflight 的封闭 finding taxonomy。
 *
 * <p>这些 code 只描述本地诊断事实，不能表示真实风控通过或交易授权。</p>
 */
public enum GateW3RiskPreflightFindingCode {
    ORDER_PREVIEW_BLOCKED,
    ORDER_PREVIEW_NOT_EVALUATED,
    RECONCILIATION_BLOCKED,
    RECONCILIATION_NOT_EVALUATED,
    RECONCILIATION_MISMATCH,
    LOCAL_ACCOUNT_UNCONFIGURED,
    LOCAL_ACCOUNT_DISABLED,
    LOCAL_ACCOUNT_SCOPE_MISMATCH,
    CREDENTIAL_METADATA_UNCONFIGURED,
    CREDENTIAL_METADATA_CONFLICT,
    MARKETDATA_QUALITY_NOT_OK,
    MIN_NOTIONAL_UNKNOWN,
    FEE_UNKNOWN,
    REMOTE_PERMISSION_UNKNOWN,
    BALANCE_NOT_EVALUATED,
    POSITION_NOT_EVALUATED,
    DAILY_LOSS_NOT_EVALUATED,
    OPEN_ORDERS_RISK_NOT_EVALUATED,
    KILL_SWITCH_NOT_EVALUATED,
    DUPLICATE_REQUEST_NOT_EVALUATED,
    RATE_LIMIT_NOT_EVALUATED,
    STATEFUL_RISK_PIPELINE_NOT_EVALUATED,
    EXECUTION_NOT_AUTHORIZED
}
