import {
    ApiOutlined,
    AreaChartOutlined,
    DashboardOutlined,
    DatabaseOutlined,
    ExperimentOutlined,
    FileSearchOutlined,
    FundProjectionScreenOutlined,
    RocketOutlined,
    ScheduleOutlined,
    SettingOutlined,
    SwapOutlined,
} from '@ant-design/icons';

import type {AppNavItem} from '@/types/navigation';

export const appNavItems: AppNavItem[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        label: 'Dashboard',
        icon: <DashboardOutlined/>,
        title: '控制台总览',
        description: '查看当前登录态、环境标识与正式控制台入口导航。',
        section: '概览',
    },
    {
        key: 'accounts',
        path: '/accounts',
        label: '账户管理',
        icon: <DatabaseOutlined/>,
        title: '账户与凭证管理',
        description: '管理当前用户的交易账户上下文、默认账户与凭证配置。',
        section: '账户与交易',
    },
    {
        key: 'trading',
        path: '/trading',
        label: '交易工作台',
        icon: <SwapOutlined/>,
        title: '交易工作台',
        description: '围绕正式账户上下文执行下单、撤单、对账、恢复与事实查询。',
        section: '账户与交易',
    },
    {
        key: 'instruments',
        path: '/instruments',
        label: 'Instrument Catalog',
        icon: <DatabaseOutlined/>,
        title: 'Instrument Catalog',
        description: '查看并同步正式 instrument/symbol catalog。',
        section: '市场与主数据',
    },
    {
        key: 'marketdata',
        path: '/marketdata',
        label: '行情查询',
        icon: <FileSearchOutlined/>,
        title: 'Marketdata',
        description: '查询正式 marketdata bars 数据范围。',
        section: '市场与主数据',
    },
    {
        key: 'adapter-readiness',
        path: '/adapter-readiness',
        label: '适配器就绪',
        icon: <ApiOutlined/>,
        title: 'Adapter Readiness',
        description: '只读查看各交易所适配器与能力的运行时 readiness（No-Real / LIVE 禁用 / 不可真实交易）。',
        section: '市场与主数据',
    },
    {
        key: 'strategies',
        path: '/strategies',
        label: '策略定义',
        icon: <SettingOutlined/>,
        title: '策略定义',
        description: '策略列表、策略详情和后续触发操作入口。',
        section: '策略运行',
    },
    {
        key: 'schedules',
        path: '/schedules',
        label: '调度计划',
        icon: <ScheduleOutlined/>,
        title: '调度计划',
        description: '调度列表、扫描任务和运行编排入口。',
        section: '策略运行',
    },
    {
        key: 'runs',
        path: '/runs',
        label: '运行记录',
        icon: <RocketOutlined/>,
        title: '运行记录',
        description: '策略运行查询、状态追踪和详情入口。',
        section: '策略运行',
    },
    {
        key: 'research',
        path: '/research',
        label: '研究配置',
        icon: <ExperimentOutlined/>,
        title: '研究配置',
        description: '研究参数列表和详情扩展点。',
        section: '研究与回测',
    },
    {
        key: 'backtests',
        path: '/backtests',
        label: '回测配置',
        icon: <FundProjectionScreenOutlined/>,
        title: '回测配置',
        description: '回测配置列表与后续创建入口。',
        section: '研究与回测',
    },
    {
        key: 'evaluations',
        path: '/evaluations',
        label: '评估结果',
        icon: <AreaChartOutlined/>,
        title: '评估结果',
        description: '评估列表、指标摘要和详情扩展点。',
        section: '研究与回测',
    },
    {
        key: 'publishes',
        path: '/publishes',
        label: '发布结果',
        icon: <FileSearchOutlined/>,
        title: '发布结果',
        description: '发布结果列表与链路审计入口。',
        section: '研究与回测',
    },
    {
        key: 'paper-trading',
        path: '/paper-trading',
        label: '模拟交易',
        icon: <SwapOutlined/>,
        title: '模拟交易',
        description: '基于已发布策略版本创建 SIM/Paper Trading run，查看运行状态与最小事实。',
        section: '策略运行',
    },
];

export function resolveMenuKey(pathname: string): string {
    const matched = [...appNavItems]
        .sort((left, right) => right.path.length - left.path.length)
        .find((item) => pathname === item.path || pathname.startsWith(`${item.path}/`));

    return matched?.key ?? 'dashboard';
}
