package com.guidinglight.nexusquant.trading.application.orderpreview;

/**
 * OrderPreviewFindingCode 是 LIMIT-only diagnostic preview 的稳定分类集合。
 *
 * <p>分类只描述结构、local venue facts 与明确未评估项，不表达下单授权。</p>
 */
public enum OrderPreviewFindingCode {
    INPUT_REQUIRED,
    EXCHANGE_NOT_SUPPORTED,
    SYMBOL_REQUIRED,
    SIDE_NOT_SUPPORTED,
    ORDER_TYPE_NOT_SUPPORTED,
    EVALUATION_TIME_REQUIRED,
    TRACE_ID_REQUIRED,
    INSTRUMENT_NOT_FOUND,
    INSTRUMENT_TYPE_NOT_SUPPORTED,
    INSTRUMENT_NOT_LIVE,
    LOCAL_FACT_READ_FAILED,
    VENUE_RULE_FACTS_MISSING,
    VENUE_RULE_FACTS_STALE,
    VENUE_RULE_SCHEMA_UNSUPPORTED,
    VENUE_RULE_CHECKSUM_INVALID,
    INVALID_PRICE,
    INVALID_QUANTITY,
    INVALID_TICK_ALIGNMENT,
    INVALID_STEP_ALIGNMENT,
    BELOW_MIN_QUANTITY,
    ABOVE_MAX_LIMIT_QUANTITY,
    ABOVE_MAX_LIMIT_NOTIONAL,
    MAX_LIMIT_QUANTITY_UNKNOWN,
    MAX_LIMIT_NOTIONAL_UNKNOWN,
    MIN_NOTIONAL_UNKNOWN,
    FEE_UNKNOWN,
    ACCOUNT_PERMISSION_UNKNOWN,
    BALANCE_NOT_EVALUATED,
    RISK_PIPELINE_NOT_EVALUATED,
    EXECUTION_NOT_AUTHORIZED
}
