COMMENT ON TABLE strategy_definitions IS '策略定义主表。保存策略注册项、启停状态和配置快照，不引入 strategyInstanceId。';
COMMENT ON TABLE strategy_schedules IS '策略调度配置表。保存策略与调度作业的关系、触发规则和去重范围，不承载单次触发实例。';
COMMENT ON TABLE strategy_runs IS '单次策略运行表。strategy_run_id 是运行级身份，request_id 仅保存首次触发请求身份。';
COMMENT ON TABLE orders IS '订单事实表。order_id 是内部主键，strategy_run_id 负责记录订单所属运行血缘。';
COMMENT ON COLUMN orders.exchange_code IS '统一交易所标识。';
COMMENT ON COLUMN orders.trade_env IS '交易环境，固定枚举为 SIM / LIVE；当前兼容口径默认 SIM。';
COMMENT ON COLUMN orders.status IS '订单状态，遵循订单生命周期状态机。';
COMMENT ON COLUMN trades.exchange_code IS '统一交易所标识。';
COMMENT ON COLUMN trades.trade_env IS '交易环境，固定枚举为 SIM / LIVE；当前兼容口径默认 SIM。';
COMMENT ON COLUMN accounts.venue IS '账户绑定交易所标识。当前仍沿用历史 venue 命名，语义对应统一交易所标识。';

COMMENT ON TABLE research_configs IS '研究配置表。保存研究配置主身份、来源策略快照与数据集规格，不直接承载执行域运行事实。';
COMMENT ON COLUMN research_configs.strategy_snapshot IS '来源策略定义快照，JSONB 保存发布前的研究输入事实；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN research_configs.config_json IS '研究配置 JSON，包括参数 schema/defaults 与 datasetSpec；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE backtest_configs IS '回测配置表。保存研究配置派生出的回测运行窗口、执行参数和评估参数。';
COMMENT ON COLUMN backtest_configs.config_json IS '回测配置快照 JSON，包括时间窗口、初始资金和 executionSpec；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_configs.evaluation_spec_json IS '评估参数 JSON，用于保存回测评估的指标口径和计算配置；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE backtest_runs IS '回测运行表。保存回测运行身份、状态、失败信息与 run 级执行摘要，不保存 sim_* 明细。';
COMMENT ON COLUMN backtest_runs.strategy_snapshot IS '运行时引用的来源策略快照；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.backtest_config_snapshot IS '运行时引用的回测配置快照；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.summary_json IS 'run 级执行摘要 JSON。只保存统计摘要，不保存 sim_* 明细事实、敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE sim_orders IS '模拟订单事实表。保存回测执行过程中生成的模拟订单，不复用实盘 orders 表。';
COMMENT ON TABLE sim_trades IS '模拟成交事实表。保存由模拟订单撮合生成的成交结果，不复用实盘 trades 表。';
COMMENT ON TABLE sim_positions IS '模拟持仓事实表。保存 run + symbol 维度的当前持仓，不复用实盘 positions 投影。';
COMMENT ON TABLE sim_pnl_snapshots IS '模拟权益快照表。保存回测运行过程中逐时点的现金、权益与 PnL 原始序列。';
COMMENT ON TABLE backtest_eval_reports IS '回测评估报告表。保存 run 级评估结果、关键指标与评估失败信息，不改写 sim_* 事实。';
COMMENT ON COLUMN backtest_eval_reports.report_json IS '评估明细 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE backtest_publish_records IS '研究产物发布记录表。保存回测运行到执行域 strategy_definition 的发布事实、来源快照与失败信息。';
COMMENT ON COLUMN backtest_publish_records.publish_snapshot_json IS '发布映射快照 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_publish_records.evaluation_summary_json IS '发布时固化的评估摘要 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE exchange_accounts IS '交易账户配置表。保存用户维度下的交易所账户、环境、别名与默认账户口径，是 legacy accounts 向正式账户模型迁移后的主承载表。';
COMMENT ON TABLE exchange_account_credentials IS '交易账户凭证版本表。保存账户对应交易所凭证的密文版本、激活状态、校验状态与轮换关系，不以 env/yml 作为正式主数据源。';
COMMENT ON TABLE marketdata_bars IS '历史行情 K 线表。保存交易所、交易对、周期和时间窗口维度下的 OHLCV 数据，作为 historical marketdata 查询主来源。';
COMMENT ON COLUMN marketdata_bars.market_type IS '市场类型，当前业务范围为 SPOT；纳入唯一键以固定不同市场类型的数据隔离语义。';
COMMENT ON COLUMN marketdata_bars.raw_payload_json IS '交易所原始 K 线 payload 快照 JSONB，仅保存当前 bar 的原始数组/对象用于审计和排障，不作为业务查询主结构；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE instrument_catalog IS 'instrument 主数据目录。统一沉淀交易所原生 symbol 与内部 symbol、精度、资产对等基础信息。';
COMMENT ON TABLE marketdata_ingestion_jobs IS '行情历史数据接入任务表，记录按交易所、市场类型、交易对、周期和时间范围创建的历史 K 线拉取任务。';
COMMENT ON COLUMN marketdata_ingestion_jobs.exchange_code IS '交易所代码，当前业务范围为 OKX、BINANCE。';
COMMENT ON COLUMN marketdata_ingestion_jobs.market_type IS '市场类型，当前业务范围为 SPOT。';
COMMENT ON COLUMN marketdata_ingestion_jobs.symbol IS '系统内部交易对代码，当前业务范围为 BTC-USDT、ETH-USDT、SOL-USDT。';
COMMENT ON COLUMN marketdata_ingestion_jobs."interval" IS 'K 线周期，当前业务范围为 1m、5m、15m、1h、4h、1d。';
COMMENT ON COLUMN marketdata_ingestion_jobs.source IS '任务来源，EXCHANGE_HISTORICAL 表示交易所历史 K 线接入。';
COMMENT ON COLUMN marketdata_ingestion_jobs.request_json IS '任务创建时的原始请求快照 JSONB，用于审计和复盘；仅保存 API 请求字段，不保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE marketdata_ingestion_runs IS '行情历史数据接入运行记录表，记录每次 run-once 的执行结果和统计信息。';
COMMENT ON COLUMN marketdata_ingestion_runs.requested_end_time IS '本次运行实际请求的结束时间，不超过任务 end_time。';
COMMENT ON COLUMN marketdata_ingestion_runs.raw_summary_json IS '本次运行的原始统计摘要 JSONB，用于排障、审计和复盘；保存计数、断点和非敏感错误码，不保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE marketdata_datasets IS '行情数据集定义表，描述可绑定回测配置的历史 K 线数据范围、质量状态和来源。';
COMMENT ON COLUMN marketdata_datasets.exchange_code IS '交易所代码，当前业务范围为 OKX、BINANCE。';
COMMENT ON COLUMN marketdata_datasets.market_type IS '市场类型，当前业务范围为 SPOT。';
COMMENT ON COLUMN marketdata_datasets.symbol IS '系统内部交易对代码，当前业务范围为 BTC-USDT、ETH-USDT、SOL-USDT。';
COMMENT ON COLUMN marketdata_datasets."interval" IS 'K 线周期，当前业务范围为 1m、5m、15m、1h、4h、1d。';
COMMENT ON COLUMN marketdata_datasets.source IS '数据集来源，当前从 marketdata_bars 派生。';
COMMENT ON COLUMN marketdata_datasets.request_json IS '数据集创建请求快照 JSONB，仅保存范围、symbol、interval 等审计字段，不保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE marketdata_dataset_coverage IS '行情数据集覆盖与质量统计表，记录每次 refresh-quality 的覆盖率和缺口摘要。';
COMMENT ON COLUMN marketdata_dataset_coverage.duplicate_bars IS '重复 K 线数量；在 marketdata_bars 唯一约束生效时正常应为 0。';
COMMENT ON COLUMN marketdata_dataset_coverage.summary_json IS '覆盖统计摘要 JSONB，用于记录 expected/actual/missing/invalid/duplicate 和数据来源，不作为主查询字段；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_configs.dataset_id IS '绑定的数据集 ID，对应 marketdata_datasets.dataset_id；为空表示尚未绑定正式数据集。';
COMMENT ON COLUMN backtest_configs.dataset_snapshot_json IS '回测配置绑定数据集时保存的数据集快照 JSONB，用于配置详情和后续 run 溯源；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.dataset_snapshot_json IS '回测运行创建时从 backtest_configs 固化的数据集快照 JSONB，用于历史运行复盘与评估/发布溯源；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE strategy_versions IS '策略版本表，记录策略定义可用于回测、发布和 Paper Trading 的不可变版本快照。';
COMMENT ON COLUMN strategy_versions.status IS '策略版本状态，允许值：DRAFT、ACTIVE、ARCHIVED；用于版本管理和发布引用。';
COMMENT ON COLUMN strategy_versions.updated_at IS '策略版本最后更新时间，通常只随状态维护变化。';
COMMENT ON COLUMN backtest_publish_records.strategy_version_id IS '发布记录绑定的策略版本 ID，对应 strategy_versions.strategy_version_id；为空表示历史发布记录尚未绑定版本。';
COMMENT ON COLUMN backtest_publish_records.version_snapshot_json IS '发布时固化的策略版本快照 JSON，包含策略编码、版本号、参数、配置、来源和 checksum；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON COLUMN backtest_configs.strategy_version_id IS '回测配置绑定的策略版本 ID，对应 strategy_versions.strategy_version_id；为空表示尚未绑定策略版本。';
COMMENT ON COLUMN backtest_configs.strategy_version_snapshot_json IS '回测配置绑定策略版本时固化的策略版本快照 JSONB，包含策略编码、版本号、状态、参数、配置、来源和 checksum；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_configs.param_snapshot_json IS '回测配置绑定策略版本时固化的参数快照 JSONB，用作后续 run 输入追溯；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_configs.config_snapshot_json IS '回测配置自身的配置快照 JSONB，从既有 config_json 回填，用于与策略版本配置快照区分；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.strategy_version_id IS '回测运行创建时从 backtest_configs 固化的策略版本 ID；后续配置重新绑定不会改写历史 run。';
COMMENT ON COLUMN backtest_runs.strategy_version_snapshot_json IS '回测运行创建时固化的策略版本快照 JSONB，用于历史运行、评估报告和后续发布追溯；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.param_snapshot_json IS '回测运行创建时固化的参数快照 JSONB，来自回测配置绑定的策略版本参数快照；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_runs.config_snapshot_json IS '回测运行创建时固化的回测配置快照 JSONB，从 backtest_config_snapshot 回填；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN backtest_eval_reports.total_return IS '评估总收益指标，与既有 total_return_rate 同口径，固定为 net_pnl / initial_capital。';
COMMENT ON COLUMN backtest_eval_reports.annualized_return IS '年化收益率指标，按评估权益快照首尾时间差折算；时间差不可用时为空。';
COMMENT ON COLUMN backtest_eval_reports.profit_loss_ratio IS '盈亏比指标，固定口径为闭合盈利交易总收益 / 闭合亏损交易绝对值；亏损为 0 时返回 0。';
COMMENT ON COLUMN backtest_eval_reports.metrics_json IS '评估核心指标汇总 JSONB，保存 total_return、annualized_return、max_drawdown、win_rate、profit_loss_ratio、trade_count、sharpe_ratio 等展示指标；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE paper_trading_runs IS 'Paper Trading 运行实例表：记录基于 publish_id 的 SIM/Paper 运行实例，固化 publish/strategy version/dataset/param/config 快照，作为风控回写、资金曲线、复盘和异常停机的输入。';
COMMENT ON COLUMN paper_trading_runs.trade_env IS 'Paper run 交易环境，固定为 SIM 或 LIVE；当前只允许 SIM。';
COMMENT ON COLUMN paper_trading_runs.market_type IS 'Paper run 市场类型，当前为 SPOT，不承载合约全量交易。';
COMMENT ON TABLE paper_trading_orders IS 'Paper Trading 模拟订单记录：记录 Paper run 产生的订单事实，用于追踪模拟订单生命周期、成交关联和风控审计，不接入真实交易所下单接口。';
COMMENT ON COLUMN paper_trading_orders.symbol IS '订单交易对，需与 publish 链路引用的数据集和现货 symbol 对齐。';
COMMENT ON COLUMN paper_trading_orders.order_type IS '订单类型，当前支持 MARKET 或 LIMIT，不承载合约下单类型。';
COMMENT ON COLUMN paper_trading_orders.raw_signal_json IS 'Paper 订单触发信号快照 JSONB，可保存策略版本/参数摘要；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE paper_trading_trades IS 'Paper Trading 模拟成交记录：记录 Paper run 订单的成交事实。';
COMMENT ON COLUMN paper_trading_trades.fee IS '成交手续费，口径取自 config_snapshot 的 feeRate；缺省为 0。';
COMMENT ON TABLE paper_trading_positions IS 'Paper Trading 模拟持仓记录：记录 Paper run 当前持仓与已实现/未实现盈亏；按 (paper_run_id, symbol) 唯一。';
COMMENT ON COLUMN paper_trading_positions.quantity IS '当前净持仓数量，可为 0；不区分多空，当前只记录现货净仓。';
COMMENT ON COLUMN paper_trading_positions.unrealized_pnl IS '未实现盈亏，由资金/持仓曲线和撮合结果维护。';
COMMENT ON COLUMN paper_trading_positions.realized_pnl IS '已实现盈亏累计值，由资金/持仓曲线和撮合结果维护。';

COMMENT ON TABLE paper_risk_check_results IS 'Paper Trading 风控检查结果表：记录 Paper run 的风控检查事实，当前只做基础健康检查，不接复杂风控策略平台。';
COMMENT ON COLUMN paper_risk_check_results.check_type IS '风控检查类型，当前为 BASIC_HEALTH_CHECK；后续可扩展 POSITION_LIMIT、DRAWDOWN_LIMIT 等。';
COMMENT ON COLUMN paper_risk_check_results.input_snapshot_json IS '风控检查输入快照 JSONB，保存检查时的 run/position/equity 摘要；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN paper_risk_check_results.result_snapshot_json IS '风控检查输出快照 JSONB，保存检查结果详情；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE equity_curve_snapshots IS 'Paper Trading 资金曲线快照表：记录 Paper run 的权益时间序列，用于资金曲线展示和回撤计算。';
COMMENT ON COLUMN equity_curve_snapshots.drawdown IS '当前回撤值，口径为 (peak_equity - current_equity) / peak_equity。';
COMMENT ON TABLE position_curve_snapshots IS 'Paper Trading 持仓曲线快照表：记录 Paper run 按 symbol 的持仓时间序列，用于持仓曲线展示。';
COMMENT ON TABLE trade_replay_records IS 'Paper Trading 交易复盘记录表：保存 Paper run 的交易决策审计链路，用于单笔交易复盘。';
COMMENT ON COLUMN trade_replay_records.decision_snapshot_json IS '决策快照 JSONB，保存策略信号和参数摘要；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN trade_replay_records.risk_snapshot_json IS '风控快照 JSONB，保存风控检查输入输出摘要；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN trade_replay_records.market_snapshot_json IS '市场快照 JSONB，保存事件时刻行情摘要；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON TABLE emergency_stop_events IS 'Paper Trading 异常停机事件表：记录 Paper run 的紧急停机触发、执行和解除事实；只作用于 SIM/Paper，不触发真实 LIVE 下单或撤单。';
COMMENT ON COLUMN emergency_stop_events.request_json IS '停机请求快照 JSONB，保存触发时的请求参数；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN emergency_stop_events.result_json IS '停机结果快照 JSONB，保存执行结果和错误信息；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON COLUMN ledger_events.payload_json IS '账本事件载荷 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN event_store.payload_json IS '事件载荷 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
COMMENT ON COLUMN audit_logs.detail_json IS '审计详情 JSON；不得保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';

COMMENT ON TABLE paper_run_stability_checks IS 'Paper run 稳定性检查结果，用于记录指定时间窗口内心跳、告警、调度失败和恢复事件的统计判定。';
COMMENT ON COLUMN paper_run_stability_checks.stability_check_id IS '稳定性检查 ID，格式 stb-<uuid>。';
COMMENT ON COLUMN paper_run_stability_checks.check_window_start IS '检查窗口开始时间（UTC，含）。';
COMMENT ON COLUMN paper_run_stability_checks.check_window_end IS '检查窗口结束时间（UTC，不含），必须严格大于 start。';
COMMENT ON COLUMN paper_run_stability_checks.status IS '检查状态：PASSED / FAILED / PARTIAL；按心跳、未处理严重告警和失败触发数判定，不等同于连续运行最终接受记录。';
COMMENT ON COLUMN paper_run_stability_checks.uptime_ratio IS '在线率（0~1，4 位小数）；heartbeat_count > 0 且无 CRITICAL 未处理告警且 failed_fire_count = 0 视为 1.0，否则按监控口径折算。';
COMMENT ON COLUMN paper_run_stability_checks.summary_json IS '稳定性检查摘要 JSON（明细计数 / CRITICAL 告警列表 / 判定原因），不保存敏感凭证、访问令牌、账户私密材料或可用于账户访问的信息。';
