package com.guidinglight.nexusquant.adapter.okx.service;

/**
 * 脱敏、fail-closed 的 GateW-2 transport/probe 错误分类。
 */
public enum OkxPrivateReadError {
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    HTTP_RATE_LIMITED,
    HTTP_SERVER_ERROR,
    HTTP_UNEXPECTED_STATUS,
    OKX_AUTHENTICATION_FAILED,
    OKX_SIGNATURE_INVALID,
    OKX_TIMESTAMP_INVALID,
    OKX_IP_NOT_ALLOWED,
    OKX_PERMISSION_DENIED,
    OKX_BUSINESS_REJECTED,
    RESPONSE_PARSE_FAILED,
    RESPONSE_CONTRACT_MISMATCH,
    NETWORK_TIMEOUT,
    NETWORK_IO_ERROR,
    NETWORK_FAILURE,
    TIMEOUT,
    REDIRECT_REJECTED,
    RESPONSE_TOO_LARGE,
    MALFORMED_RESPONSE,
    HTTP_ERROR,
    OKX_PROVIDER_ERROR,
    AUTHENTICATION_FAILURE,
    INVALID_API_KEY,
    SIGNATURE_FAILURE,
    IP_ALLOWLIST_FAILED,
    PERMISSION_BLOCKED,
    RATE_LIMITED,
    CLOCK_SKEW,
    ENVIRONMENT_MISMATCH,
    PARTIAL_RESPONSE,
    CREDENTIAL_UNAVAILABLE,
    CREDENTIAL_CONFLICT,
    ACCOUNT_SCOPE_MISMATCH
}
