package com.guidinglight.nexusquant.trading.application.reconciliation;

/** GateW-3 只读订单快照比较的封闭分类；分类本身不触发修复或状态迁移。 */
public enum ReconciliationTaxonomy {
    MATCHED,
    LOCAL_ONLY,
    REMOTE_ONLY,
    STATUS_MISMATCH,
    PRICE_MISMATCH,
    QUANTITY_MISMATCH,
    FILLED_QUANTITY_MISMATCH,
    SYMBOL_MISMATCH,
    SIDE_MISMATCH,
    ORDER_TYPE_MISMATCH,
    CLIENT_ORDER_ID_MISMATCH,
    SNAPSHOT_SCOPE_MISMATCH,
    DUPLICATE_LOCAL_ID,
    DUPLICATE_REMOTE_ID,
    UNMATCHED_IDENTITY,
    UNMAPPABLE_REMOTE_STATUS,
    STALE_LOCAL_SNAPSHOT,
    STALE_REMOTE_SNAPSHOT,
    PARTIAL_REMOTE_SNAPSHOT,
    REMOTE_PERMISSION_UNKNOWN,
    REMOTE_NOT_EVALUATED,
    EXECUTION_NOT_AUTHORIZED
}
