package com.guidinglight.nexusquant.trading.application.safety;

/**
 * GateW-4 operational safety 的脱敏 reason code。
 *
 * <p>这些值只解释诊断结果；不表示交易、LIVE、订单或资金操作获得授权。</p>
 */
public enum OperationalSafetyAssessmentFindingCode {
    KILL_SWITCH_ENGAGED,
    KILL_SWITCH_UNKNOWN,
    KILL_SWITCH_STORAGE_FAILURE,
    DATABASE_UNAVAILABLE,
    RECONCILIATION_STALE,
    RECONCILIATION_PARTIAL,
    PRIVATE_PROBE_FAILURE,
    CREDENTIAL_UNAVAILABLE,
    CREDENTIAL_CONFLICT,
    RESTORE_FAILURE,
    MARKETDATA_STALE,
    HUMAN_REVIEW_EVIDENCE_MISSING,
    HUMAN_REVIEW_EVIDENCE_STALE,
    HUMAN_REVIEW_EVIDENCE_CONFLICT,
    PERSISTENCE_RETENTION_NOT_PROVEN,
    BACKUP_RESTORE_NOT_PROVEN,
    INCIDENT_DRILL_INCOMPLETE,
    LOCAL_SOAK_NOT_PROVEN,
    REAL_READONLY_SOAK_NOT_EVALUATED,
    REAL_READONLY_SOAK_CREDENTIAL_REQUIRED
}
